# Generated by Django 4.1.1 on 2022-11-24 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 25, 2, 37, 4, 846852)),
        ),
    ]
